name = "personal-console-sync-proxy"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
APPS_SCRIPT_EXEC = "https://script.google.com/macros/s/AKfycbx05PRTxlEHqcofb14LnhqTDJR9JsD498nFDwJ4a3aMXBvYMjXsnWkdUa2tL7dgQq5mHg/exec"
